Repository themesberg/flowbite-vue, pull requests merged in 2022-12, with the labels that each got.

#87 feat: support ESM file extension
  package.json
  yarn.lock
Labels: good first issue

#77 Add basic carousel component (Issue #55)
  docs/components/carousel/carousel.md
  docs/components/carousel/examples/CarouselAutomaticSlideExample.vue
  docs/components/carousel/examples/CarouselDefaultExample.vue
  docs/components/carousel/examples/CarouselNoControlsExample.vue
  docs/components/carousel/examples/CarouselNoIndicatorsExample.vue
  docs/components/carousel/examples/CarouselPicturesExample.vue
  docs/components/carousel/examples/CarouselSlideExample.vue
  docs/components/carousel/examples/CarouselSlideIntervalExample.vue
  src/components/Carousel/Carousel.vue
Labels: good first issue, new component

#113 feat: Added New Rating component (basic)
  docs/components/rating/examples/RatingCountExample.vue
  docs/components/rating/examples/RatingExample.vue
  docs/components/rating/examples/RatingStarSizesExample.vue
  docs/components/rating/examples/RatingWithTextExample.vue
  docs/components/rating/rating.md
  src/components/Rating/Rating.vue
  src/components/Rating/composables/useRatingClasses.ts
  src/components/Rating/types.ts
Labels: new component

#117 docs: Updated links
  .github/workflows/node.js.yml
  docs/.vitepress/config.ts
  docs/components/accordion.md
  docs/components/alert.md
  docs/components/avatar.md
  docs/components/badge.md
  docs/components/breadcrumb.md
  docs/components/button-group.md
  docs/components/button.md
  docs/components/card.md
  docs/components/carousel.md
  docs/components/dropdown.md
  docs/components/footer.md
  docs/components/input.md
  docs/components/list-group.md
  docs/components/modal.md
  docs/components/navbar.md
  docs/components/pagination.md
  docs/components/progress.md
  docs/components/rating.md
  docs/components/sidebar.md
  docs/components/spinner.md
  docs/components/table.md
  docs/components/tabs.md
  docs/components/timeline.md
  docs/components/toast.md
  docs/components/tooltip.md
Labels: documentation

#124 docs: add missing Button import
  docs/components/input.md
Labels: bug, good first issue
