Repository themesberg/flowbite-vue, pull requests merged in 2023-06, with the labels that each got.

#138 Avatar - Allow placeholder override, and handle image errors
  docs/components/avatar.md
  docs/components/avatar/examples/AvatarAlternativePlaceholderExample.vue
  src/components/Avatar/Avatar.vue
Labels: enhancement, good first issue

#136 Add @click for TabPane component
  docs/components/tabs.md
  src/components/Tabs/Tabs.vue
Labels: enhancement, good first issue

#150 feat(component): Select component
  .eslintrc.js
  docs/.vitepress/config.ts
  docs/components/select.md
  docs/components/select/examples/DisabledSelect.vue
  docs/components/select/examples/SelectExample.vue
  docs/components/select/examples/SelectSize.vue
  docs/components/select/examples/UnderlinedSelect.vue
  src/components/Select/Select.vue
  src/components/Select/composables/useSelectClasses.ts
  src/components/Select/types.ts
  src/index.ts
Labels: good first issue, new component

#151 feat(component): New checkbox component
  docs/.vitepress/config.ts
  docs/.vitepress/theme/clear.css
  docs/assets/logo.svg
  docs/components/checkbox.md
  docs/components/checkbox/examples/CheckboxChecked.vue
  docs/components/checkbox/examples/CheckboxDefault.vue
  docs/components/checkbox/examples/CheckboxDisabled.vue
  docs/components/checkbox/examples/CheckboxLink.vue
  docs/index.md
  src/components/Checkbox/Checkbox.vue
  src/components/Checkbox/composables/useCheckboxClasses.ts
Labels: new component

#152 feat(component): New toggle component
  docs/.vitepress/config.ts
  docs/components/toggle.md
  docs/components/toggle/examples/CheckedToggle.vue
  docs/components/toggle/examples/ColorsToggle.vue
  docs/components/toggle/examples/DefaultToggle.vue
  docs/components/toggle/examples/DisabledToggle.vue
  docs/components/toggle/examples/SizeToggle.vue
  src/components/Toggle/Toggle.vue
  src/components/Toggle/composables/useToggleClasses.ts
  src/index.ts
Labels: new component

#155 feat(component): New range slider
  docs/.vitepress/config.ts
  docs/components/range.md
  docs/components/range/examples/DefaultRange.vue
  docs/components/range/examples/DisabledRange.vue
  docs/components/range/examples/MinMaxRange.vue
  docs/components/range/examples/SizeRange.vue
  docs/components/range/examples/StepsRange.vue
  src/components/Range/Range.vue
  src/components/Range/composables/useRangeClasses.ts
  src/index.ts
Labels: new component

#156 Update input props schema
  docs/components/input.md
  docs/components/input/examples/InputExample.vue
  src/components/Input/Input.vue
Labels: enhancement
