Repository themesberg/flowbite-vue, pull requests merged in 2024-08, with the labels that each got.

#311 Blockquote component
  docs/.vitepress/config.mts
  docs/components/blockquote.md
  docs/components/typography/blockquote/FwbBlockquoteAlignExample.vue
  docs/components/typography/blockquote/FwbBlockquoteExample.vue
  docs/components/typography/blockquote/FwbBlockquoteSizeExample.vue
  docs/components/typography/blockquote/FwbBlockquoteSolidExample.vue
  src/components/Typography/FwbBlockquote.vue
  src/index.ts
Labels: 🔧 enhancement, 📦 new component

#303 fix: Fixed issue with AccordionPanel onUnmounted callback
  src/components/FwbAccordion/FwbAccordionPanel.vue
Labels: 🪲 bug, 🔧 enhancement, ✨ good first issue

#301 feat(dropdown): add show/hide events
  docs/components/dropdown.md
  src/components/FwbDropdown/FwbDropdown.vue
Labels: 🔧 enhancement, ✨ good first issue

#296 feat: Toggle label position
  docs/components/toggle.md
  docs/components/toggle/examples/FwbToggleExampleOrder.vue
  src/components/FwbToggle/FwbToggle.vue
  src/components/FwbToggle/composables/useToggleClasses.ts
Labels: 🔧 enhancement

#299 #298 Adjust type of prop 'link' of FwbSidebarItem.vue
  src/components/FwbSidebar/FwbSidebarItem.vue
Labels: 🔧 enhancement
