Repository themesberg/flowbite-vue, pull requests merged in 2025-01, with the labels that each got.

#322 Improved input layout to support proper positioning for right-to-left languages
  docs/components/input/examples/FwbInputExampleSuffix.vue
  src/components/FwbInput/FwbInput.vue
  src/components/FwbInput/composables/useInputClasses.ts
Labels: 🔧 enhancement

#338 Add disabled state to dropdown trigger button
  docs/components/dropdown.md
  docs/components/dropdown/examples/FwbDropdownExampleDisabled.vue
  src/components/FwbDropdown/FwbDropdown.vue
Labels: 🔧 enhancement

#339 Feature/custom dropdown classes
  .gitignore
  docs/components/dropdown.md
  docs/components/dropdown/examples/FwbDropdownExampleAlignment.vue
  docs/components/dropdown/examples/FwbDropdownExampleButtonColors.vue
  docs/components/dropdown/examples/FwbDropdownExampleButtonGroup.vue
  docs/components/dropdown/examples/FwbDropdownExampleCloseInside.vue
  docs/components/dropdown/examples/FwbDropdownExampleColors.vue
  docs/components/dropdown/examples/FwbDropdownExampleDisabled.vue
  docs/components/dropdown/examples/FwbDropdownExampleListGroup.vue
  docs/components/dropdown/examples/FwbDropdownExamplePlacement.vue
  docs/components/dropdown/examples/FwbDropdownExampleTrigger.vue
  src/components/FwbButton/FwbButton.vue
  src/components/FwbButton/composables/useButtonClasses.ts
  src/components/FwbDropdown/FwbDropdown.vue
  src/components/FwbDropdown/composables/useDropdownClasses.ts
Labels: 📚 documentation, 🔧 enhancement

#340 Fix #310 - Toast shadow not visible
  src/components/FwbToast/composables/useToastClasses.ts
Labels: 🪲 bug

#347 fix(badge): dark mode badge colours to match flowbite
  src/components/FwbBadge/composables/useBadgeClasses.ts
Labels: 🪲 bug
