Repository themesberg/flowbite-vue, pull requests merged in 2025-03, with the labels that each got.

#304 feat: Label added for FileInput dropzone
  src/components/FwbFileInput/FwbFileInput.vue
Labels: 🔧 enhancement, ✨ good first issue

#343 modelValue set to be optional in FwbInput
  src/components/FwbInput/FwbInput.vue
Labels: 🪲 bug

#256 refactor: expose `isOpen` to use in `arrow-icon` slot
  src/components/FwbSidebar/FwbSidebarDropdownItem.vue
Labels: 🔧 enhancement

#360 chore: upgrade to tailwind v4
  docs/.postcssrc.js
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.js
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/tailwind.css
  docs/pages/getting-started.md
  docs/vite.config.ts
  eslint.config.js
  package-lock.json
  package.json
  src/components/FwbButtonGroup/FwbButtonGroup.vue
  src/components/FwbDropdown/composables/useDropdownClasses.ts
  src/components/FwbFooter/FwbFooter.vue
  src/components/FwbModal/FwbModal.vue
  src/components/FwbToast/composables/useToastClasses.ts
  src/style.css
  tailwind.config.js
  vite.config.ts
Labels: 🔧 enhancement, :robot: maintenance

#361 chore: release v0.2.0
  package-lock.json
  package.json
Labels: :robot: maintenance
