Repository themesberg/flowbite-vue, pull requests merged in 2025-04, with the labels that each got.

#367 Add focus trap functionality to modal component
  docs/components/modal.md
  docs/components/modal/examples/FwbModalExample.vue
  docs/components/modal/examples/FwbModalExampleFocusTrap.vue
  package-lock.json
  package.json
  src/components/FwbModal/FwbModal.vue
Labels: 🔧 enhancement

#370 feat(list-group-item): add active prop
  docs/components/list-group.md
  docs/components/listGroup/examples/FwbListGroupExampleHover.vue
  src/components/FwbListGroup/FwbListGroupItem.vue
  src/components/FwbListGroup/composables/useListGroupItemClasses.ts
Labels: 🔧 enhancement

#371 Chore: release v0.2.1
  package-lock.json
  package.json
Labels: :robot: maintenance

#376 maintenance - unnecessary eslint-disable removed
  src/components/FwbJumbotron/FwbJumbotron.vue
  src/components/utils/FwbSlotListener/FwbSlotListener.vue
Labels: 🔧 enhancement, :robot: maintenance

#375 change linkClasses in FwbNavbarLink to be computed rather than only evaluated on mount to resolve #373
  src/components/FwbNavbar/FwbNavbarLink.vue
Labels: 🪲 bug
